services:
  # app:
  #   build: .
  #   restart: unless-stopped
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     mailhog:
  #       condition: service_started
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1027:1025
      - 8027:8025
    volumes:
      - ./docker-data/mailhog:/maildir
    networks:
      - app_network

networks:
  app_network:
    driver: bridge